export const HTTP_ERROR = Object.freeze({
  ACCESS_DENIED: 403,
  NOT_FOUND: 404,
  TIME_OUT: 402,
  BAD_REQUEST: 400,
  NOT_AUTHENTICATE: 401,
  INTERNAL_SERVER_ERROR: 500
});


export const FIELD_ERROR = {
  INVALID: "INVALID",
  EMAIL_NOT_ACTIVE: "EMAIL_NOT_ACTIVE",
  USER_NOT_ACTIVE: "USER_NOT_ACTIVE",
  WRONG_PASSWORD: "WRONG_PASSWORD",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  EMAIL_INVALID: "EMAIL_INVALID",
  INVALID_TOKEN: "INVALID_TOKEN",
  EMAIL_NOT_FOUND: "EMAIL_NOT_FOUND",
  EMAIL_EXISTED: "EMAIL_EXISTED",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  PASSWORD_NOT_MATCH: "PASSWORD_NOT_MATCH",
  UPLOAD_FAILED: "UPLOAD_FAILED",
  USER_NAME_IS_EXITED: "USER_NAME_IS_EXITED",
  CURRENT_PASSWORD_NOT_MATCH: "CURRENT_PASSWORD_NOT_MATCH",
  CURRENT_EMAIL_NOT_MATCH: "CURRENT_EMAIL_NOT_MATCH",
  CONFIRM_EMAIL_NOT_MATCH: "CONFIRM_EMAIL_NOT_MATCH",
  USERNAME_IS_A_REQUIRED_FIELD: "USERNAME_IS_A_REQUIRED_FIELD",
  EXISTED: "EXISTED",
  BAD_REQUEST: "BAD_REQUEST",
  NOT_AUTHENTICATE: "NOT_AUTHENTICATE",
  FORBIDDEN_ERROR: "FORBIDDEN_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR"
};