components:
    schemas:
        MessageDTO:
            type: object
            properties:
                id:
                    type: string
                    example: 'msg_123456'
                senderId:
                    type: string
                    example: 'user_abc'
                content:
                    type: string
                    example: 'Hello, this is a message.'
                contentType:
                    type: string
                    example: 'TEXT'
                caseId:
                    type: string
                    example: 'case_789'
                createdAt:
                    type: string
                    format: date-time
                    example: '2025-04-29T10:00:00Z'
